/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './context/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── MD3 Light Design System (ui-designs) ─────────────────────────────
        primary:                    '#000000',
        'primary-container':        '#3b3b3b',
        'primary-fixed':            '#5e5e5e',
        'primary-fixed-dim':        '#474747',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#ffffff',
        'on-primary-fixed':         '#ffffff',
        'on-primary-fixed-variant': '#e2e2e2',
        'inverse-primary':          '#c6c6c6',

        secondary:                  '#006e28',
        'secondary-container':      '#63ef7b',
        'secondary-fixed':          '#53e16f',
        'secondary-fixed-dim':      '#30c456',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#002107',
        'on-secondary-fixed':       '#002107',
        'on-secondary-fixed-variant':'#004616',

        tertiary:                   '#3b3b3b',
        'tertiary-container':       '#747474',
        'tertiary-fixed':           '#5e5e5e',
        'tertiary-fixed-dim':       '#474747',
        'on-tertiary':              '#e2e2e2',
        'on-tertiary-container':    '#ffffff',
        'on-tertiary-fixed':        '#ffffff',
        'on-tertiary-fixed-variant':'#e2e2e2',

        error:                      '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'on-error-container':       '#410002',

        surface:                    '#f9f9f9',
        'surface-dim':              '#dadada',
        'surface-bright':           '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f3f3f4',
        'surface-container':        '#eeeeee',
        'surface-container-high':   '#e8e8e8',
        'surface-container-highest':'#e2e2e2',
        'surface-variant':          '#e2e2e2',
        'surface-tint':             '#5e5e5e',
        background:                 '#f9f9f9',
        'on-surface':               '#1a1c1c',
        'on-surface-variant':       '#474747',
        'on-background':            '#1a1c1c',
        'inverse-surface':          '#2f3131',
        'inverse-on-surface':       '#f0f1f1',
        outline:                    '#777777',
        'outline-variant':          '#c6c6c6',

        // ── Legacy tokens (keep for any remaining references) ─────────────────
        navy:      '#0D1221',
        card:      '#141C2E',
        'card-hi': '#1B2540',
        blue:      '#3B82F6',
        'blue-dim':'#1D4ED8',
        amber:     '#F59E0B',
        danger:    '#EF4444',
        alarm:     '#1A0808',
        success:   '#10B981',
        snow:      '#D8E2F0',
        mist:      '#7C8FA8',
        'mist-hi': '#A3B3C8',
        violet:    '#8B5CF6',
      },
      fontFamily: {
        body: ['var(--font-inter)', 'sans-serif'],
      },
      keyframes: {
        ring: {
          '0%':   { transform: 'rotate(0)' },
          '5%':   { transform: 'rotate(12deg)' },
          '10%':  { transform: 'rotate(-12deg)' },
          '15%':  { transform: 'rotate(8deg)' },
          '20%':  { transform: 'rotate(-8deg)' },
          '25%':  { transform: 'rotate(0)' },
          '100%': { transform: 'rotate(0)' },
        },
        'breathe': {
          '0%, 100%': { transform: 'scale(1)',    opacity: '0.7' },
          '50%':      { transform: 'scale(1.08)', opacity: '1'   },
        },
        'breathe-ring': {
          '0%, 100%': { transform: 'scale(1)',    opacity: '0.3' },
          '50%':      { transform: 'scale(1.18)', opacity: '0.08'},
        },
        'pulse-soft': {
          '0%, 100%': { transform: 'scale(0.95)', opacity: '1'   },
          '50%':      { transform: 'scale(1.1)',  opacity: '0.7' },
        },
        'pulse-ring': {
          '0%':   { transform: 'scale(0.8)', opacity: '0.5' },
          '50%':  { transform: 'scale(1.1)', opacity: '0.2' },
          '100%': { transform: 'scale(0.8)', opacity: '0.5' },
        },
        'alarm-pulse': {
          '0%, 100%': { transform: 'scale(1)',    opacity: '0.5' },
          '50%':      { transform: 'scale(1.22)', opacity: '0.15'},
        },
        'fade-up': {
          '0%':   { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)'    },
        },
        'check-in': {
          '0%':   { transform: 'scale(0.4)', opacity: '0' },
          '65%':  { transform: 'scale(1.12)' },
          '100%': { transform: 'scale(1)',   opacity: '1' },
        },
        'glow-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '15%': { transform: 'translateX(-8px)' },
          '30%': { transform: 'translateX(8px)' },
          '45%': { transform: 'translateX(-5px)' },
          '60%': { transform: 'translateX(5px)' },
          '75%': { transform: 'translateX(-2px)' },
          '90%': { transform: 'translateX(2px)' },
        },
        'slide-up': {
          '0%':   { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)',     opacity: '1' },
        },
      },
      animation: {
        'bell':         'ring 2.5s ease-in-out infinite',
        'breathe':      'breathe 4s ease-in-out infinite',
        'breathe-ring': 'breathe-ring 4s ease-in-out infinite',
        'pulse-soft':   'pulse-soft 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'pulse-ring':   'pulse-ring 2s cubic-bezier(0.4,0,0.6,1) infinite',
        'alarm-pulse':  'alarm-pulse 1.4s ease-in-out infinite',
        'fade-up':      'fade-up 0.5s ease-out both',
        'check-in':     'check-in 0.55s cubic-bezier(0.34,1.56,0.64,1) both',
        'glow-in':      'glow-in 0.8s ease-out both',
        'shake':        'shake 0.5s ease-in-out',
        'slide-up':     'slide-up 0.4s ease-out both',
      },
    },
  },
  plugins: [],
}
