/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './context/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#000000',
        'on-primary': '#e2e2e2',
        'primary-container': '#3b3b3b',
        'on-primary-container': '#ffffff',
        'primary-fixed': '#5e5e5e',
        'primary-fixed-dim': '#474747',
        'on-primary-fixed': '#ffffff',
        'on-primary-fixed-variant': '#e2e2e2',
        'secondary': '#006e28',
        'on-secondary': '#ffffff',
        'secondary-container': '#63ef7b',
        'on-secondary-container': '#002107',
        'secondary-fixed': '#53e16f',
        'secondary-fixed-dim': '#30c456',
        'on-secondary-fixed': '#002107',
        'on-secondary-fixed-variant': '#004616',
        'tertiary': '#3b3b3b',
        'on-tertiary': '#e2e2e2',
        'tertiary-container': '#747474',
        'on-tertiary-container': '#ffffff',
        'tertiary-fixed': '#5e5e5e',
        'tertiary-fixed-dim': '#474747',
        'on-tertiary-fixed': '#ffffff',
        'on-tertiary-fixed-variant': '#e2e2e2',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',
        'surface': '#f9f9f9',
        'surface-bright': '#f9f9f9',
        'surface-dim': '#dadada',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#474747',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#5e5e5e',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        'inverse-primary': '#c6c6c6',
        'outline': '#777777',
        'outline-variant': '#c6c6c6',
        'background': '#f9f9f9',
        'on-background': '#1a1c1c',
      },
      fontFamily: {
        headline: ['var(--font-inter)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      keyframes: {
        ring: {
          '0%': { transform: 'rotate(0)' },
          '5%': { transform: 'rotate(15deg)' },
          '10%': { transform: 'rotate(-15deg)' },
          '15%': { transform: 'rotate(10deg)' },
          '20%': { transform: 'rotate(-10deg)' },
          '25%': { transform: 'rotate(0)' },
          '100%': { transform: 'rotate(0)' },
        },
        'pulse-soft': {
          '0%': { transform: 'scale(0.95)', opacity: '1' },
          '50%': { transform: 'scale(1.1)', opacity: '0.7' },
          '100%': { transform: 'scale(0.95)', opacity: '1' },
        },
        'pulse-alarm': {
          '0%': { transform: 'scale(0.8)', opacity: '0.5' },
          '50%': { transform: 'scale(1.1)', opacity: '0.2' },
          '100%': { transform: 'scale(0.8)', opacity: '0.5' },
        },
      },
      animation: {
        'bell': 'ring 2s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-alarm': 'pulse-alarm 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
