export const NASHVILLE_STOPS = [
  {
    id: 'downtown-transit-center',
    name: 'Downtown Transit Center',
    address: '5th Ave & Commerce St, Nashville',
    lat: 36.1627,
    lng: -86.7816,
    routes: ['Bus 3', 'Bus 8', 'Bus 22', 'Bus 55'],
  },
  {
    id: 'vandy-west-end',
    name: 'Vanderbilt University',
    address: 'West End Ave & 21st Ave S, Nashville',
    lat: 36.1447,
    lng: -86.8027,
    routes: ['Bus 3'],
  },
  {
    id: 'belmont-blvd',
    name: 'Belmont Blvd & Linden Ave',
    address: 'Belmont Blvd at Linden Ave, Nashville',
    lat: 36.1332,
    lng: -86.7914,
    routes: ['Bus 17'],
  },
  {
    id: 'hillsboro-village',
    name: 'Hillsboro Village',
    address: '21st Ave S & Acklen Ave, Nashville',
    lat: 36.1376,
    lng: -86.8080,
    routes: ['Bus 3', 'Bus 17'],
  },
  {
    id: 'green-hills',
    name: 'Green Hills Mall',
    address: 'Abbott Martin Rd & Hillsboro Pike, Nashville',
    lat: 36.1091,
    lng: -86.8150,
    routes: ['Bus 17'],
  },
  {
    id: '100-oaks',
    name: '100 Oaks Transit Hub',
    address: 'Powell Ave at Nolensville Pike, Nashville',
    lat: 36.1058,
    lng: -86.7591,
    routes: ['Bus 55'],
  },
  {
    id: 'antioch',
    name: 'Antioch — Murfreesboro Pike',
    address: 'Murfreesboro Pike & Antioch Pike, Nashville',
    lat: 36.0627,
    lng: -86.6726,
    routes: ['Bus 55'],
  },
  {
    id: 'bna-airport',
    name: 'BNA Airport Terminal A',
    address: 'One Terminal Dr, Nashville',
    lat: 36.1263,
    lng: -86.6774,
    routes: ['Bus 18'],
  },
  {
    id: 'east-nashville',
    name: 'East Nashville — Gallatin Ave',
    address: 'Gallatin Ave & Holly St, Nashville',
    lat: 36.1782,
    lng: -86.7510,
    routes: ['Bus 22'],
  },
  {
    id: 'riverfront-station',
    name: 'WeGo Star — Riverfront Station',
    address: 'Riverfront Park, Nashville',
    lat: 36.1624,
    lng: -86.7784,
    routes: ['WeGo Star'],
  },
  {
    id: 'donelson-station',
    name: 'WeGo Star — Donelson Station',
    address: 'Lebanon Pike & Donelson Pike, Nashville',
    lat: 36.1522,
    lng: -86.6964,
    routes: ['WeGo Star'],
  },
  {
    id: 'hermitage-station',
    name: 'WeGo Star — Hermitage Station',
    address: 'Andrew Jackson Pkwy, Hermitage',
    lat: 36.1726,
    lng: -86.6141,
    routes: ['WeGo Star'],
  },
]
